export const ASSETS_MANIFEST = 'assets-manifest.json'
export const CONFIG_MANIFEST = 'config-manifest.json'
export const RUNTIME_NAME = 'webpack-runtime'
export const HTML_WEBPACK_PLUGIN = 'HtmlWebpackPlugin'
export const GLOBAl_VARIABLE = '__global_variable__'
export const JSONP_FUNCTION = 'webpackJsonp'
